version: '3.5'

services:

  landlorater.io:
    container_name: landlorater.io
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development


  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./production-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/landlorater.ml/fullchain.pem:/etc/letsencrypt/live/landlorater.ml/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/landlorater.ml/privkey.pem:/etc/letsencrypt/live/landlorater.ml/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
